M48
; DRILL file {KiCad (6.0.5)} date Sun Jan 21 09:57:28 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-21T09:57:28+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
%
G90
G05
T1
X167.0Y-99.0
X172.0Y-94.0
X172.0Y-104.0
X174.5Y-94.0
X174.5Y-104.0
T0
M30
